version: "3.11.2"
services:
  app:
    build: .
      - .:/photogram
    ports:
    - 8000:8000
    image: photogram
    container_name: photogram_container
    command: gunicorn config.wsgi:application -- bind 0.0.0.0:8000
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    image: nginx
    links:
      - app